// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSubasta.Repository;

#nullable disable

namespace ProyectoSubasta.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20251116184023_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PostorSubasta", b =>
                {
                    b.Property<int>("PostoresDni")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubastasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostoresDni", "SubastasId");

                    b.HasIndex("SubastasId");

                    b.ToTable("PostorSubasta");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Postor", b =>
                {
                    b.Property<int>("Dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Dni");

                    b.ToTable("Postores");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Articulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GanadorDni")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPuja")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pujas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubastadorDni")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GanadorDni");

                    b.HasIndex("SubastadorDni");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subastador", b =>
                {
                    b.Property<int>("Dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Dni");

                    b.ToTable("Subastadores");
                });

            modelBuilder.Entity("PostorSubasta", b =>
                {
                    b.HasOne("ProyectoSubasta.Models.Postor", null)
                        .WithMany()
                        .HasForeignKey("PostoresDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoSubasta.Models.Subasta", null)
                        .WithMany()
                        .HasForeignKey("SubastasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subasta", b =>
                {
                    b.HasOne("ProyectoSubasta.Models.Postor", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorDni");

                    b.HasOne("ProyectoSubasta.Models.Subastador", "Subastador")
                        .WithMany()
                        .HasForeignKey("SubastadorDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Subastador");
                });
#pragma warning restore 612, 618
        }
    }
}
