// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSubasta.Repository;

#nullable disable

namespace ProyectoSubasta.Migrations
{
    [DbContext(typeof(SubastaContext))]
    partial class SubastaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ProyectoSubasta.Models.Postor", b =>
                {
                    b.Property<int>("Dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Subastaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Dni");

                    b.HasIndex("Subastaid");

                    b.ToTable("Postores");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subasta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Articulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GanadorDni")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPuja")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pujas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubastadorDni")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("GanadorDni");

                    b.HasIndex("SubastadorDni");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subastador", b =>
                {
                    b.Property<int>("Dni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Dni");

                    b.ToTable("Subastadores");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Postor", b =>
                {
                    b.HasOne("ProyectoSubasta.Models.Subasta", null)
                        .WithMany("Postores")
                        .HasForeignKey("Subastaid");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subasta", b =>
                {
                    b.HasOne("ProyectoSubasta.Models.Postor", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorDni");

                    b.HasOne("ProyectoSubasta.Models.Subastador", "Subastador")
                        .WithMany()
                        .HasForeignKey("SubastadorDni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Subastador");
                });

            modelBuilder.Entity("ProyectoSubasta.Models.Subasta", b =>
                {
                    b.Navigation("Postores");
                });
#pragma warning restore 612, 618
        }
    }
}
